# Site settings
title: My Blog       # Replace with your site title
author: Phoebe Farrelly             # Replace with your name
description: >               # A short description of your site
  This is my blog made from GitHub pages, powered by Jekyll and the Minima theme.

# Theme
theme: minima

# Optional settings
url: ""                       # The base hostname & protocol for your site, leave empty for local
baseurl: ""                   # The subpath of your site, e.g. /blog
